name: Label Check

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled
      - opened
      - reopened

permissions:
  statuses: write

env:
  BLOCK_LABEL: Block

jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - name: Set status check to pending
        if: contains(github.event.pull_request.labels.*.name, env.BLOCK_LABEL) == true
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{github.repository}}/statuses/${{github.event.pull_request.head.sha}} \
            --header 'authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
            --header 'content-type: application/json' \
            --data '{
              "context": "Merge Block Check",
              "state": "pending",
              "description": "You can merge by removing `${{env.BLOCK_LABEL}}` label."
            }'
      - name: Set status check to success
        if: contains(github.event.pull_request.labels.*.name, env.BLOCK_LABEL) == false
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{github.repository}}/statuses/${{github.event.pull_request.head.sha}} \
            --header 'authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
            --header 'content-type: application/json' \
            --data '{
              "context": "Merge Block Check",
              "state": "success",
              "description": "Can be merged. You can block this PR by adding `${{env.BLOCK_LABEL}}` label."
            }'
